openapi: 3.0.1
info:
    title: Python Runner
    description: 实时运行文心一言生成的python代码。
    version: "v1"
servers:
    - url: http://localhost:8081
paths:
    /run_python:
        post:
            operationId: run_python
            summary: 运行python代码
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            required: [code]
                            properties:
                                code:
                                    type: string
                                    description: 需要运行的python代码
            responses:
                "200":
                    description: 代码运行成功
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/python_result"
    /load_run_bar:
        get:
            operationId: load_run_bar
            summary: 获取代码的运行按钮
            responses:
                "200":
                    description: 获取成功
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/load_run_bar"
            x-return-raw:
                description: 标记当前 API 请求的结果是否经过大模型，当 name 的值不空时，从插件结果中获取具体字段，类型必须 String，直接返回，而不经过大模型。
                mediaType: application/json
                name: this_is_a_field_name
                type: string


components:
    schemas:
        python_result:
            type: object
            required: [result, error]
            properties:
                result:
                    type: string
                    description: 运行结果
                error:
                    type: string
                    description: 错误信息
        load_run_bar:
            type: object
            required: [img]
            properties:
                img:
                    type: string
                    description: 运行按钮的图片url